name: Update README

concurrency:
  group: "main"
  cancel-in-progress: false

on:
  push: {branches: ["master", "main"]}
  schedule:
    [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip 
      - name: Update README
        run: |
          python3 --version
          cd updating
          python3 -m pip install -r requirements.txt
          python3 main.py
      - name: Commit to the repo
        run: |
          git config user.name "MAINTENANCE INTERN"
          git config user.email ""
          git add .
          git commit -m 'Refresh Internships' || echo
          git push -f origin main
