name: Update Internships

on:
  schedule:
  - cron: "0 0 * * *" # Run the workflow every day at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.1 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip requests

      - name: Move to the directory
        run: cd ./updating

      - name: Execute Python script # Run the run.py to get the latest data
        run: python main.py
